# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b0c6569de68fb8f3b083ca08bc60728c724fc007cef9ab63b93f61d050d4e0b27781403cde7db37e9236db7976a899810b25fd4ecadd594254c6dd263708fe4

test:
  secret_key_base: 16cfefda9401eb792bef340f864f8e685ff0fb174743d26432e49830bdfeb31e75ed1bdca1c2ade9045a5d1bcfe5d20be67653c9ed5fbaf00fd7184740fa931f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
